version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: piejin/kittygram_final_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image:  piejin/kittygram_final_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: piejin/kittygram_final_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static